---
#home_dir: "/var/www/lgsp/"
admin_user: ""
admin_pass: ""

userstore_dsname: "WSO2_UM_DB"
userstore_jndi: "jdbc/WSO2UMDB"
userstore_connection_string: "jdbc:mysql://localhost:3306/LGSP-userstore?characterEncoding=UTF-8&amp;useSSL=false&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC"
userstore_user: ""
userstore_pass: ""
userstore_driver_class: "com.mysql.cj.jdbc.Driver"

identity_dsname: "WSO2_IDENTITY_DB"
identity_jndi: "jdbc/WSO2_IDENTITY_DB"
identity_connection_string: "jdbc:mysql://localhost:3306/LGSP-identity?characterEncoding=UTF-8&amp;useSSL=false&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC"
identity_user: ""
identity_pass: ""
identity_driver_class: "com.mysql.cj.jdbc.Driver"

registry_dsname: "WSO2REG_DB"
registry_jndi: "jdbc/WSO2REG_DB"
registry_connection_string: "jdbc:mysql://localhost:3306/LGSP-registry?characterEncoding=UTF-8&amp;useSSL=false&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC"
registry_user: ""
registry_pass: ""
registry_driver_class: "com.mysql.cj.jdbc.Driver"
registry_config_name: "govregistry"
registry_remote_instance_id: "gov"

ei_port: 9443
bps_port: 9445
am_port: 9447
is_port: 9448